### ISSUE TITLE
Inner pages: Page content spills outside the content area background.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#101]
![image](https://cloud.githubusercontent.com/assets/11186313/11356823/45fb43ba-929c-11e5-8493-a9441310a6a2.png)

**Comment by isaq-titan** [comment]
This is Implemented as per the PSD provided, please find the below attached screenshot.
![screenshot-adventure](https://cloud.githubusercontent.com/assets/13450822/11395809/323ff274-9393-11e5-96aa-d199ea69913a.jpg)

**Comment by roseliesromeo** [comment]
I am referring to this rectangle layer. Page content should be within this container.
![image](https://cloud.githubusercontent.com/assets/11186313/11413070/be2b2b5a-941f-11e5-8df6-381f0e36d6ea.png)

**Comment by roseliesromeo** [comment]
Not fixed.
Is the transparent background part of the background image? It is a separate background/layer as per design.
