### ISSUE TITLE
Footer:  Incorrect footer SEO ranking used.  It should be #5 per scope.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#13]
![image](https://cloud.githubusercontent.com/assets/11186313/10599642/768eded2-7736-11e5-912c-99c6240c3d1b.png)

**Comment by roseliesromeo** [comment]
Not fixes.  Lacking "http://www.titanweb.com.au" before the image/logo.

**Comment by isaq-titan** [comment]
If I add the link here, it will not be as per the design, please let me know if you still want me to add the "http://www.titanweb.com.au" before the image/logo.

**Comment by roseliesromeo** [comment]
We'll just adhere to what is specified in the scope.
![image](https://cloud.githubusercontent.com/assets/11186313/11177252/337062b6-8c7f-11e5-8f3e-6f8257e203d2.png)
