### ISSUE TITLE
Admin - enquire now form: Description won't display in front end.  

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#14]
![image](https://cloud.githubusercontent.com/assets/11186313/10655847/0ecff404-78ab-11e5-8892-123a7788fba3.png)

**Comment by isaq-titan** [comment]
AS per the design the description should not be displayed there, and even our team leader did not mentioned anything about it in the scope.

**Comment by roseliesromeo** [comment]
We need to display if ever there is description/instruction in the field.  We can always leave it blank if there is none. That is the function of the description field.

**Comment by isaq-titan** [comment]
Can you please let me know how many lines of description you would like me to display here, so that I can implement the description accordingly.

**Comment by roseliesromeo** [comment]
One line will do. Something like "Please fill in the fields below."

**Comment by roseliesromeo** [comment]
It will only display in home page not in the enquire form of the inner pages.
![image](https://cloud.githubusercontent.com/assets/11186313/11234625/c1c7ded2-8e04-11e5-8262-4b5152278145.png)
