### ISSUE TITLE
General: Images used are with watermarks.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#2]
https://knowledgebase.titanweb.com.au/implementation-practices/page-section-contents/using-images
![image](https://cloud.githubusercontent.com/assets/11186313/10597352/a9c1548a-7720-11e5-9edf-4b34eed8ecbd.png)

**Comment by isaq-titan** [comment]
Removed the images and fixed according to the Bug No. #51
