### ISSUE TITLE
About us: Listed content isn't displayed in two columns.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#49]
![image](https://cloud.githubusercontent.com/assets/11186313/10684199/0075cc94-797d-11e5-8cb6-f3100aed86e5.png)

**Comment by isaq-titan** [comment]
It has been done as per the PSD provided which has two different layouts for both About Us and Services.

**Comment by isaq-titan** [comment]
In About Us Page PSD it has only one column. Please check the attachement.
![02-adv-about](https://cloud.githubusercontent.com/assets/13450822/11123036/e5588cdc-8983-11e5-9066-17a3f9756c9c.jpg)
