### ISSUE TITLE
News page: User is unable to add intro text in the news page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#54]

**Comment by isaq-titan** [comment]
When we are selecting the News Page as Default Posts Page, the content editor will be hidden and we will not be able to add the content to it. That is the reason it is also not mentioned in the scope.

**Comment by roseliesromeo** [comment]
There is a big possibility that user would like to input intro text in the page.  Also, it is in our standards to make sure all pages can be inputted.

It has been done for the following sites.  Kindly refer:
http://thesamaritans.stage.titanweb.com.au/news-events/news/
http://rangsboomerangs.stage.titanweb.com.au/news/
http://wamarble.stage.titanweb.com.au/news/

**Comment by isaq-titan** [comment]
with a recent update on Titan's default theme the option to add content has been disabled, please check the attached screenshot and If you would still like me to add the content section I can do it by using the ACF field.

![screenshot-posts-default](https://cloud.githubusercontent.com/assets/13450822/11120707/ba19ddf2-8977-11e5-9073-c35632089a18.jpg)

**Comment by roseliesromeo** [comment]
No need to use acf.  Just enable the page editor.
Please refer to this site:
http://thewillandprobatecentre.stage.titanweb.com.au/wp-admin/post.php?post=1502&action=edit
