### ISSUE TITLE
Mobile - header: Main menu navigation bar doesn't occupy the entire width of the screen.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#75]
iPad air (portrait)
![image](https://cloud.githubusercontent.com/assets/11186313/10686280/1587dd94-7995-11e5-8177-8b84fbe4817a.png)

**Comment by roseliesromeo** [comment]
Please apply fixes to iTouch 5

**Comment by isaq-titan** [comment]
I do not see any gap beside the main navigation in Itouch (Potrait and Landscape)
