### ISSUE TITLE
General: Toggled yes for the inner banner display option but inner banner isn't displayed in front end.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#79]
Applicable to the following pages:
Products
Gallery
News
Contact us
![image](https://cloud.githubusercontent.com/assets/11186313/10988842/0eb05960-847b-11e5-8160-ab658bc590e1.png)

**Comment by isaq-titan** [comment]
Now the option is not visible for Products, Gallery, Contact Us and News page.
