### ISSUE TITLE
Product single page: Product images are cropped.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Adventure4x4#91]
![image](https://cloud.githubusercontent.com/assets/11186313/11057794/008b0500-87c9-11e5-8bdf-474d87678d58.png)

**Comment by roseliesromeo** [comment]
Apply fixes to products category page.
![image](https://cloud.githubusercontent.com/assets/11186313/11237658/412fbdea-8e1c-11e5-815f-8f67042ce6a0.png)

**Comment by roseliesromeo** [comment]
Product are still cropped
![image](https://cloud.githubusercontent.com/assets/11186313/11332897/75961660-9204-11e5-8df9-ce5ea2eee9cc.png)

**Comment by roseliesromeo** [comment]
Not fixed for featured image in the single page.
![image](https://cloud.githubusercontent.com/assets/11186313/11413244/cb291626-9421-11e5-9ce3-5c2f2dbeb0b0.png)

**Comment by isaq-titan** [comment]
Due to some cache it might not be displaying, you can upload a new image and then select it as a featured image, it works fine.
